### ISSUE TITLE
Shortcode / PHP not working

### ISSUE THREAD

**Issue by rmulr** [getbowtied/Hook-Me-Up#1]
Hello there,

i downloaded your wonderful plugin to customize some parts of my single product pages. 

However i noticed i will need to add some shortcode including php code or php code directly to the Theme Customizers Hook Me Up Editor Section but this is not working. 

I tried installing Plugins like "PHP Everywhere" or "Enable Shortcode and PHP in Text widget" but this won´t make a change too. 

Any idea how to do this?

I would simply like to have a shortcode or php added like

```
[xyz-ips snippet="product-extra"]
<?php echo "some extra stuff.."; ?>
```

thanks in advance

**Comment by rthvanesa** [comment]
Hello @lddd,

Thanks for reaching out.
You should be able to use shortcodes but it wasn’t built to work with PHP and I don’t have a anything in mind that would help you go around it.
If the shortcode doesn’t work, please make sure it works in other areas, such as a page, or try other shortcodes. Just to make sure the actual shortcode isn’t the problem in case it doesn’t get executed.
Cheers,
Vanesa

**Comment by rmulr** [comment]
Thank you, got it working now :)
