### ISSUE TITLE
woocommerce_before_add_to_cart_form is below 'Stock' info

### ISSUE THREAD

**Issue by sensei83** [getbowtied/Hook-Me-Up#2]
Hi
I am using Shopkeeper theme and I added content to woocommerce_before_add_to_cart_form 
Issue:  woocommerce_before_add_to_cart_form is below 'Stock' info
Expected result: Stock info is below woocommerce_before_add_to_cart_form

Example product: https://www.sixkros.com/product/gps-smart-leather-wallet/

How can I solve it?

**Comment by rthvanesa** [comment]
Hello @sensei83 !

Thanks for using our products!
This is the order in which WooCommerce plugin displays them. If you want to display the hook above the stock info, you have to overwrite the WooCommerce template into your child theme and change their order manually.
Take a look into Shopkeeper theme's folder. See _woocommerce/single-product/add-to-cart/simple.php_ file. This is the file you will have to overwrite. Copy this file to your child theme, making sure you keep the exact same folders in which it is placed (it should look like this: shopkeeper-child/woocommerce/single-product/add-to-cart/simple.php).
Then edit this file.
On line 26 you will see: `echo wc_get_stock_html( $product );`
On line 30 you will see: `<?php do_action( 'woocommerce_before_add_to_cart_form' ); ?>`
You will have to delete line 26 and add  `<?php echo wc_get_stock_html( $product ); ?>` right below line 30.

Please try that and let me know if you get the expected result. If you have any other question, please don't hesitate to ask me.
