### ISSUE TITLE
Variations form hooks

### ISSUE THREAD

**Issue by b-nik** [getbowtied/Hook-Me-Up#4]
Great plugin! I wanted to add some text in the product page, above the variation selection form.

Woocommerce has this hook: woocommerce_before_variations_form 

However the plugin doesn't seem to offer this option yet.

**Comment by rthvanesa** [comment]
Hello and sorry for the huge delay.

The 'woocommerce_before_variations_form' hook has been included in the latest plugin update.

Thank you for using our plugin!
Happy Friday!
